// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddedgenderdobcolumnstoUserInfo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedgenderdobcolumnstoUserInfo));
        
        string IMigrationMetadata.Id
        {
            get { return "201609070746251_Added gender,dob columns to UserInfo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
